name: Bonjour
on:
  - push
jobs:
  dire_bonjour_por_favor:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/dduportal/esgi-gitpod
      options: --user=root
    steps:
      - uses: actions/checkout@v4
      - run: npm clean-install
      - run: npm run lint