name: Bonjour
on:
  push:
  pull_request:
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      - run: docker image build --tag="${IMAGE_NAME}" ./
      - run: docker container run --volume="$(pwd)":/app "${IMAGE_NAME}" npm run lint
  dockerhub:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - name: "Login to Docker Hub"
        uses: docker/login-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          username: "sairkko"
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
      - name: "Push if on `main`"
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: ./
          tags: "sairkko/sayhello:${{ github.ref_name }}"
