name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4 # Récupère le contenu du dépôt correspondant au commit du workflow en cours
      - uses: actions/setup-node@v4
        with:
          node-version: 23
      - run: npm install
      - run: npm run lint